FROM nginx:1.19.10

EXPOSE 3001

COPY /config/nginx.conf /etc/nginx/nginx.conf
COPY /frontend /usr/share/nginx/html

# COPY config/nginx/init.sh /docker-entrypoint.d/30-terminal-scripts.sh
# RUN chmod +x /docker-entrypoint.d/30-terminal-scripts.sh
# COPY config/nginx/templates/app.conf.template /etc/nginx/templates/app.conf.template
# COPY config/nginx/partials /etc/nginx/partials

# COPY --from=backend /var/www/backend/ /var/www/backend/
# COPY --from=node /var/www/build/build /var/www/frontend/

# WORKDIR /var/www/frontend

# RUN cp index.html index.html.template