version: "3.9"

services:
  frontend-install:
    build:
      context: .
      dockerfile: Dockerfile-frontend-install
    volumes:
      - node_modules:/node_modules
      - ./frontend:/app
    command: npm install
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    depends_on:
      - frontend-install
    volumes:
      - node_modules:/node_modules
      - ./frontend:/app
    ports:
      - '5173:5173'
    command: npm run dev
  backend-install:
    build:
      context: .
      dockerfile: Dockerfile-backend-install
    volumes:
      - vendor:/vendor
      - ./backend:/app
    command: composer install
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    depends_on:
      - backend-install
    volumes:
      - vendor:/vendor
      - ./backend:/app
    ports:
      - '3003:3003'
    command: php artisan serve
volumes:
  node_modules:
    name: terminal-node_modules
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app
  vendor:
    name: terminal-vendor
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app
