version: "3.9"

services:
  frontend-install:
    build:
      context: .
      dockerfile: Dockerfile-frontend-install
    volumes:
      - node_modules:/node_modules
      - ./frontend:/app
    command: npm install
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    depends_on:
      - frontend-install
    volumes:
      - node_modules:/node_modules
      - ./frontend:/app
    ports:
      - '5173:5173'
    command: npm run dev
  backend-install:
    build:
      context: .
      dockerfile: Dockerfile-backend-install
    volumes:
      - vendor:/vendor
      - ./backend:/app
    command: composer install
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    depends_on:
      - backend-install
      - mysql
    volumes:
      - vendor:/vendor
      - ./backend:/app
    ports:
      - '8000:8000'
    command: php artisan serve --host=0.0.0.0
    networks:
      - terminal
  mysql:
    image: mariadb:10.4
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: officedot2
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - terminal
    ports:
      - "3306:3306"
volumes:
  dbdata:
  node_modules:
    name: terminal-node_modules
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app
  vendor:
    name: terminal-vendor
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app
networks:
  terminal:
    driver: bridge