version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - '3000:80'
volumes:
  node_modules:
    name: terminal-node_modules
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /app
